name: Host Images for PyPI

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  host-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Verify images exist
      run: |
        echo "Checking for images in assets folder..."
        ls -la assests/
        echo "Images found:"
        find assests/ -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif"
        
    - name: Create image URLs
      run: |
        echo "## Image URLs for PyPI" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### AWDX Banner" >> $GITHUB_STEP_SUMMARY
        echo "https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX.png" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Profile Management Commands" >> $GITHUB_STEP_SUMMARY
        echo "https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX_PROFILE_HELP.png" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Usage in README.md" >> $GITHUB_STEP_SUMMARY
        echo "Replace local paths with:" >> $GITHUB_STEP_SUMMARY
        echo "- \`assests/AWDX.png\` → \`https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX.png\`" >> $GITHUB_STEP_SUMMARY
        echo "- \`assests/AWDX_PROFILE_HELP.png\` → \`https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX_PROFILE_HELP.png\`" >> $GITHUB_STEP_SUMMARY
        
    - name: Comment on commit
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.repos.listCommitComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha
          });
          
          if (comments.length === 0) {
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `## 🖼️ Images Hosted Successfully!
              
              Your images are now available at:
              
              **AWDX Banner:**
              https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX.png
              
              **Profile Management Commands:**
              https://raw.githubusercontent.com/pxkundu/awdx/development/assests/AWDX_PROFILE_HELP.png
              
              Update your README.md to use these URLs for PyPI display!`
            });
          } 